name: deep_learning
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10.*
  - pip
  - pytorch
  - torch-scatter
  - pytorch-lightning
  - lightning
  - tokenizers
  - transformers
  - pip:
      - numpy==1.25.1
      - tqdm==4.66.2
      - pandas==1.1.4
      - h5py==3.12.1
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.7
      - click==8.1.7
      - scikit-learn==0.24.2
      - x-transformers==1.16.23